#!/usr/bin/env ruby
#
# This is: script/generate_cities_seed_from_csv
#
require 'seed-fu'
require 'rubygems'
require 'fastercsv'
require 'csv'
#require File.join( File.dirname(__FILE__), '..', 'vendor/plugins/seed-fu/lib/seed-fu/writer' )

# Maybe SEEF_FILE could be $stdout, hm.
#
CALC_COMPONENTS = "/Users/npisenti/Desktop/CalculusComponents.csv"
# CALC_COMPONENTS = File.join( File.dirname(__FILE__), '..', 'CalculusComponents.csv' )
# SEED_FILE = File.join( File.dirname(__FILE__), '..', 'db', 'fixtures', 'test.rb' )
SEED_FILE = "/Users/npisenti/Desktop/CalculusComponents-out.rb"

puts "its doing something"
# Create a seed_writer, walk the CSV, add to the file.
seed_writer = SeedFu::Writer.new({
  :class_name => 'Component',
  :seed_by => [:id]
})

seed_writer.write(SEED_FILE) do |writer|
  CSV.foreach( CALC_COMPONENTS, :return_headers => false, :headers => :first_row) do |row|
    # Write the seed
    writer.add({
      :id => row['DB_id'],
      :course_id => 2,
      :name => row['name'],
      :description => row['description']
    })
  end
end
